blog/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('news/', views.news, name="news"),
    path('search/', views.search_function, name="search_url"),
    path('news/<slug:slug>/', views.post_detail, name="post_detail_url"),
    path('news/<slug:slug>/comment/', views.comment, name ="comment"),
    path('categories/<slug:slug>/', views.category_detail, name="category_detail_url"),
    path('register/', views.register, name="register"),
    path('sort/', views.sort, name="sort"),
]

start/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models
from django.utils import timezone
from django.shortcuts import reverse
from django.contrib.auth.models import User

class Category(models.Model):
    title = models.CharField("Заголовок", max_length=255)
    slug = models.SlugField("Ссылка", unique=True)
    image = models.ImageField("Картинка", blank=True, null=True)

    class Meta:
        verbose_name = "Категория"
        verbose_name_plural = "Категории"

    def get_absolute_url(self):
        return reverse('category_detail_url', kwargs={'slug': self.slug})

    def __str__(self):
        return self.title

class Post(models.Model):
    title = models.CharField("Заголовок", max_length=255)
    slug = models.SlugField("Ссылка", unique=True)
    image = models.ImageField("Картинка", blank=True, null=True)
    category = models.ForeignKey(Category, on_delete=models.SET_NULL, null=True, blank=True, verbose_name="Категория")
    content = models.TextField("Текст")
    date = models.DateTimeField("Дата", default=timezone.now)
    publish = models.BooleanField("Опубликавано", default=False)
    views = models.IntegerField('Просмотри', default=0)

    class Meta:
        verbose_name = "Новость"
        verbose_name_plural = "Новосты"

    def get_absolute_url(self):
        return reverse('post_detail_url', kwargs={'slug': self.slug})

    def __str__(self):
        return self.title


class Comment(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name="Автор")
    post = models.ForeignKey(Post, on_delete=models.CASCADE, verbose_name="Новость")
    text = models.TextField("Текст коментарии")
    date = models.DateField("Дата", default=timezone.now)

    class Meta:
        verbose_name = "Коментарий"
        verbose_name_plural = "Коментарии"

    def __str__(self):
        return self.user.username

blog/forms.py
from django.contrib.auth.forms import UserCreationForm
from django import forms
from django.contrib.auth.models import User

class RegisterForm(UserCreationForm):
    username = forms.CharField(label="Никнейм", required=True, widget=forms.TextInput(attrs={'class':'form-control mb-20'}))
    password1 = forms.CharField(label="Парол", required=True, widget=forms.PasswordInput(attrs={'class':'form-control mb-20'}))
    password2 = forms.CharField(label="Подтверждения пароля", required=True, widget=forms.PasswordInput(attrs={'class':'form-control mb-20'}))
    email = forms.EmailField(label="Email", required=True, widget=forms.TextInput(attrs={'class':'form-control mb-20'}))
    first_name = forms.CharField(label="Имя", required=True, widget=forms.TextInput(attrs={'class':'form-control mb-20'}))
    last_name = forms.CharField(label="Фамилия", required=True, widget=forms.TextInput(attrs={'class':'form-control mb-20'}))

    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2', 'first_name', 'last_name',)

    def save(self, commit=True):
        user = super().save(commit=False)
        user.email = self.cleaned_date['email']
        user.first_name = self.cleaned_date['first_name']
        user.last_name = self.cleaned_date['last_name']
        if commit:
            user.save()
            return user

blog/views.py
from django.shortcuts import render, redirect, reverse
from .models import Post, Category
from django.db.models import Q
from .forms import RegisterForm

def index(request):
    posts = Post.objects.filter(publish = 1).order_by('-views')[:3]
    sliders = Post.objects.filter(publish = 1).filter(views__gte = 10).order_by('-views')[:6]
    categories = Category.objects.all()[:12]
    context = {'news': posts, 'sliders': sliders, 'categories': categories}
    return render(request, 'blog/index.html', context)

def news(request):
    posts = Post.objects.all()
    return render(request, 'blog/news.html', {'posts': posts})

def search_function(request):
    query = request.GET.get('search_input')
    posts = Post.objects.filter(Q(title__icontains=query))
    return render(request, 'blog/search.html', {'query': query, 'posts': posts})

def post_detail(request, slug):
    post = Post.objects.get(slug__exact = slug)
    post.views += 1
    post.save()
    return render(request, 'blog/post_detail.html', {'post': post})

def category_detail(request, slug):
    category = Category.objects.get(slug__exact = slug)
    return render(request, 'blog/category_detail.html', {'category': category})

def register(request):
    if not request.user.is_authenticated:
        if request.method == 'POST':
            form = RegisterForm(request.POST)
            if form.is_valid():
                form.save()
                return redirect('login')
        else:
            form = RegisterForm()
        return render(request, 'blog/register.html', {'form': form})
    return redirect('index')

def comment(request, slug):
    post = Post.objects.get(slug__exact = slug)
    if request.method == 'POST':
        post.comment_set.create(
            user = request.user,
            text = request.POST.get('text')
        )
        return redirect(reverse('post_detail_url', kwargs={'slug': post.slug}))
    return redirect(reverse('post_detail_url', kwargs={'slug': post.slug}))
      
def sort(request):
    query = request.GET.get('sort')
    posts = Post.objects.order_by(query)
    return render(request, 'blog/sort.html', {'posts': posts, 'query': query})

blog/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="{% static 'bootstrap.min.css' %}">
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="#">Navbar</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
      
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item">
              <a class="nav-link" href="{% url 'index' %}">Главная</a>
            </li>
            {% if not user.is_authenticated %}
            <li class="nav-item">
              <a class="nav-link" href="{% url 'register' %}">Регистрация</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'login' %}">Вход</a>
            </li>
            {% else %}
            <li class="nav-item">
              <a class="nav-link" href="{% url 'logout' %}">Выход</a>
            </li>
            {% endif %}
          </ul>
          <form action="{% url 'search_url' %}" method="GET" class="form-inline my-2 my-lg-0">
            <input name="search_input" class="form-control mr-sm-2" type="search" placeholder="Поиск..." aria-label="Search">
            <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Поиск</button>
          </form>
        </div>
      </nav>
    {% block content %}
    {% endblock %}
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
<scriptsrc="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
<script src="{% static 'bootstrap.min.js' %}"></script>
</body>
</html>

blog/templates/blog/category_detail.html
{% extends 'base.html' %}

{% block title %}
{{category.title}}
{% endblock %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col-md-9" style="padding: 20px;">
        {% if category in image.url != null%}
            <img 
            src="{{category.image.url}}" style="width: 100%; height: 300px; object-fit: cover;" alt="">
        {% endif %}
        <h3>{{category.title}}</h3>
        <hr>
        <div class="row">
            {% for post in category.post_set.all %}
            <div class="col-md-4">
              <div class="card">
                {% if post.image.url != null %}
                  <img style="height: 200px; object-fit: cover;" src="{{post.image.url}}" class="card-img-top" alt="...">
                {% endif %}
                  <div class="card-body">
                    <h5 class="card-title">{{post.title}}</h5>
                    <p class="card-text">{{post.content|safe|slice:"0:100"}}...</p>
                    <a href="{{post.category.get_absolute_url}}" class="btn btn-primary">{{post.category.title}}</a>
                  </div>
              </div>
            </div>
          {% endfor %}
        </div>
        </div>
        <div class="col-md-3"></div>
    </div>
</div>
{% endblock %}

blog/templates/blog/index.html
{% extends 'base.html' %}

{% block content %}
<div id="carouselExampleCaptions" class="carousel slide" data-ride="carousel">
    <ol class="carousel-indicators">
      {% for post in sliders %}
      <li data-target="#carouselExampleCaptions" data-slide-to="{{forloop.counter0}}" {% if forloop.first %} class="active" {% endif %}></li>
      {% endfor %}
    </ol>
    <div class="carousel-inner">
      {% for post in sliders %}
      <div class="carousel-item {% if forloop.first %} active {% endif %}">
        {% if post.image.url != null%}
        <img style="height: 500px; object-fit: cover;" src="{{post.image.url}}" class="d-block w-100" alt="...">
        {% endif %}
        <div class="carousel-caption d-none d-md-block">
          <a href="{{post.get_absolute_url}}">
            <h5>{{post.title}}</h5>
          </a>
          <p>{{post.content|safe|slice:"0:100"}}...</p>
        </div>
      </div>
      {% endfor %}
    </div>
    <a class="carousel-control-prev" href="#carouselExampleCaptions" role="button" data-slide="prev">
      <span class="carousel-control-prev-icon" aria-hidden="true"></span>
      <span class="sr-only">Previous</span>
    </a>
    <a class="carousel-control-next" href="#carouselExampleCaptions" role="button" data-slide="next">
      <span class="carousel-control-next-icon" aria-hidden="true"></span>
      <span class="sr-only">Next</span>
    </a>
  </div>
  <section class="container-fluid">
      <div class="container">
          <h1 class="text-center">Популярные новости</h1>
          <hr>
          <div class="row">
            {% for post in news %}
              <div class="col-md-4">
                <div class="card">
                  {% if post.image.url != null %}
                    <img style="height: 200px; object-fit: cover;" src="{{post.image.url}}" class="card-img-top" alt="...">
                  {% endif %}
                    <div class="card-body">
                      <a href="{{post.get_absolute_url}}">
                        <h5 class="card-title">{{post.title}}</h5>
                      </a>
                      <p class="card-text">{{post.content|safe|slice:"0:100"}}...</p>
                      <b>Просмотров: {{post.views}}</b>
                      <a href="{{post.category.get_absolute_url}}" class="btn btn-primary">{{post.category.title}}</a>
                    </div>
                </div>
              </div>
            {% endfor %}
          </div>
      </div>
  </section>

  <section class="container-fluid bg-light">
      <div class="container bg-white">
          <h1 class="text-center">Популярные новости</h1>
          <hr>
          <div class="row">
            {% for category in categories %}
              <div class="col-md-2" style="margin: 10px 0;">
                <div class="card">
                  <a href="{{category.get_absolute_url}}">
                    {% if category.image.url != null %}
                    <img src="{{category.image.url}}" title="{{category.title}}" class="card-img-top" alt="...">
                    {% else %}
                    <img src="#" alt="{{category.title}}" class="card-img-top">
                    {% endif %}
                  </a>
                </div>
              </div>
            {% endfor %}
          </div>
      </div>
  </section>
{% endblock %}

blog/templates/blog/news.html
{% extends 'base.html' %}

{% block title %}
Новости 
{% endblock %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col-md-9">
            <div class="row">
                {% for post in posts %}
                    <div class="col-md-4">
                        {% if post.image.url != null%}
                            <img style="height: 200px; width: 100%; object-fit: cover;" src="{{post.image.url}}" alt="">
                        {% endif %}
                        <h3 class="text-center">{{post.title}}</h3>
                        <p>{{post.content|safe|slice:"0:100"}}</p>
                    </div>
                    {% empty %}
                    <h2>Ничего нет</h2> 
                {% endfor %}
            </div>
        </div>
        <div class="col-md-3">
            <form action="{% url 'sort' %}" method="GET">
            <select name="sort" onchange="{this.form.submit()}">
                <option value="-date">Сначала новые</option>
                <option value="date">Сначала старые</option>
                <option value="-views">Популярные</option>
                <option value="views">Непопулярные</option>
            </select>
            </form>
        </div>
    </div>
</div>

{% endblock %}

blog/templates/blog/post_detail.html
{% extends 'base.html' %}
{% load humanize %}
{% block title %}
{{post.title}} 
{% endblock %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col-md-9" style="padding: 20px;">
            {% if post.image.url != null %}
                <img src="{{post.image.url}}" style="height: 300px; width: 100%; object-fit: cover;"  alt="">
             {% endif %}
             <h3>{{post.title}}</h3>
             <p>{{post.content|safe}}</p>
             <p class="text-right">
                <b>Просмотры: {{post.views}}</b>
                <i>{{post.date|date:"d F,Y"}}</i>
             </p>
             <hr>
             <p>
                <i>комментариев: {{post.comment_set.count}}</i>
            </p>
            <h3>Оставьте ваш комментарий:</h3>
            {% if user.is_authenticated%}
                <form action="{% url 'comment' post.slug %}" method="POST">
                    {% csrf_token %}
                    <p>
                        <textarea name="text" class="form-control"></textarea>
                    </p>
                    <p class="text-right">
                        <button class="btn btn-outline-primary">Отправить</button>
                    </p>
                </form>
            {% else %}
                <p>Чтобы оставить комментарий, <a href="{% url 'register' %}">зарегистрируйтесь</a> или <a href="{% url 'login' %}">войдите</a></p>
            {% endif %}
            <hr>
            {% for comment in post.comment_set.all%}
                <div class="col-md-12">
                    <h3>{{comment.user.username}}</h3>
                    <p>
                        {{comment.text}}
                    </p>
                    <p class="text-right">
                        {{comment.date|timesince}} назад
                    </p>
                </div>
        {% endfor %}
        </div>
        <div class="col-md-3"></div>
    </div>
</div>
{% endblock %}

blog/templates/blog/register.html
{% extends 'base.html' %}

{% block title %}
Регистрация
{% endblock %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col-md-9">
            <form action="{% url 'register' %}" method="POST">
                {% csrf_token %}
                {{form.as_p}}
                <button class="btn btn-success">Регистрация</button>
            </form>
        </div>
        <div class="col-md-3"></div>
    
    </div>
</div>
{% endblock %}

blog/templates/blog/search.html
{% extends 'base.html' %}

{% block title %}
Поиск по запросу: {{query}} 
{% endblock %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col-md-9">
            <div class="row">
                {% for post in posts %}
                    <div class="col-md-4">
                        {% if post.image.url != null%}
                            <img style="height: 200px; width: 100%; object-fit: cover;" src="{{post.image.url}}" alt="">
                        {% endif %}
                        <h3 class="text-center">{{post.title}}</h3>
                        <p>{{post.content|safe|slice:"0:100"}}</p>
                    </div>
                    {% empty %}
                    <h2>Поиск по запросу "{{query}}" ничего не найдено</h2>
                {% endfor %}
            </div>
        </div>
        <div class="col-md-3"></div>
    </div>
</div>

{% endblock %}

blog/templates/blog/sort.html
{% extends 'base.html' %}

{% block title %}
Новости 
{% endblock %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col-md-9">
            <div class="row">
                {% for post in posts %}
                    <div class="col-md-4">
                        {% if post.image.url != null%}
                            <img style="height: 200px; width: 100%; object-fit: cover;" src="{{post.image.url}}" alt="">
                        {% endif %}
                        <h3 class="text-center">{{post.title}}</h3>
                        <p>{{post.content|safe|slice:"0:100"}}</p>
                    </div>
                    {% empty %}
                    <h2>Ничего нет</h2> 
                {% endfor %}
            </div>
        </div>
        <div class="col-md-3">
            <form action="{% url 'sort' %}" method="GET">
            <select name="sort" onchange="{this.form.submit()}">
                <option {% if query == '-date' %} selected {% endif %} value="-date">Сначала новые</option>
                <option {% if query == 'date' %} selected {% endif %} value="date">Сначала старые</option>
                <option {% if query == '-views' %} selected {% endif %} value="-views">Популярные</option>
                <option {% if query == 'views' %} selected {% endif %} value="views">Непопулярные</option>
            </select>
            </form>
        </div>
    </div>
</div>

{% endblock %}